/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImportRouteImport } from './routes/import'
import { Route as PanduanRouteImport } from './routes/panduan'
import { Route as LamaranIndexRouteImport } from './routes/lamaran.index'
import { Route as LamaranBaruRouteImport } from './routes/lamaran.baru'
import { Route as LamaranIdEditRouteImport } from './routes/lamaran.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const PanduanRoute = PanduanRouteImport.update({
  id: '/panduan',
  path: '/panduan',
  getParentRoute: () => rootRouteImport,
} as any)
const LamaranIndexRoute = LamaranIndexRouteImport.update({
  id: '/lamaran/',
  path: '/lamaran/',
  getParentRoute: () => rootRouteImport,
} as any)
const LamaranBaruRoute = LamaranBaruRouteImport.update({
  id: '/lamaran/baru',
  path: '/lamaran/baru',
  getParentRoute: () => rootRouteImport,
} as any)
const LamaranIdEditRoute = LamaranIdEditRouteImport.update({
  id: '/lamaran/$id/edit',
  path: '/lamaran/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/panduan': typeof PanduanRoute
  '/lamaran/baru': typeof LamaranBaruRoute
  '/lamaran/': typeof LamaranIndexRoute
  '/lamaran/$id/edit': typeof LamaranIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/panduan': typeof PanduanRoute
  '/lamaran/baru': typeof LamaranBaruRoute
  '/lamaran': typeof LamaranIndexRoute
  '/lamaran/$id/edit': typeof LamaranIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/panduan': typeof PanduanRoute
  '/lamaran/baru': typeof LamaranBaruRoute
  '/lamaran/': typeof LamaranIndexRoute
  '/lamaran/$id/edit': typeof LamaranIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/import'
    | '/panduan'
    | '/lamaran/baru'
    | '/lamaran/'
    | '/lamaran/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/import'
    | '/panduan'
    | '/lamaran/baru'
    | '/lamaran'
    | '/lamaran/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/import'
    | '/panduan'
    | '/lamaran/baru'
    | '/lamaran/'
    | '/lamaran/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImportRoute: typeof ImportRoute
  PanduanRoute: typeof PanduanRoute
  LamaranBaruRoute: typeof LamaranBaruRoute
  LamaranIndexRoute: typeof LamaranIndexRoute
  LamaranIdEditRoute: typeof LamaranIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panduan': {
      id: '/panduan'
      path: '/panduan'
      fullPath: '/panduan'
      preLoaderRoute: typeof PanduanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lamaran/': {
      id: '/lamaran/'
      path: '/lamaran'
      fullPath: '/lamaran/'
      preLoaderRoute: typeof LamaranIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lamaran/baru': {
      id: '/lamaran/baru'
      path: '/lamaran/baru'
      fullPath: '/lamaran/baru'
      preLoaderRoute: typeof LamaranBaruRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lamaran/$id/edit': {
      id: '/lamaran/$id/edit'
      path: '/lamaran/$id/edit'
      fullPath: '/lamaran/$id/edit'
      preLoaderRoute: typeof LamaranIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImportRoute: ImportRoute,
  PanduanRoute: PanduanRoute,
  LamaranBaruRoute: LamaranBaruRoute,
  LamaranIndexRoute: LamaranIndexRoute,
  LamaranIdEditRoute: LamaranIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
